title: Lucerne
description: A web framework for Common Lisp
baseurl: "/lucerne"
url: "http://eudoxia.me"

markdown: kramdown

# Links
links:
  crane: http://eudoxia0.github.io/crane/
  postmodern: http://marijnhaverbeke.nl/postmodern/
  wookie: http://wookie.beeets.com/
  hunchentoot: http://weitz.de/hunchentoot/
